### ISSUE TITLE
A way to run all the tests and ignore the ones that have the ScreenshotInstrumentation annotation

### ISSUE THREAD

**Issue by joao-sixtostart** [ndtp/android-testify#100]
**Is your feature request related to a problem? Please describe.**
A way to run all `connectedAndroidTests` in the project (running all the modules tests) but ignore the screenshot tests

**Describe the solution you'd like**
The same way we can run only `./gradlew screenshotTest`, have a way to ignore all that have the `ScreenshotInstrumentation` annotation

**Comment by DanielJette** [comment]
@joao-sixtostart 

Thank you for the feedback.

It is possible to run all non-screenshot instrumentation tests with `connectedAndroidTests`. Fortunately, all Testify screenshot tests must be annotated with `@ScreenshotInstrumentation` and so we only need to filter out tests with those annotations.

To filter out the screenshot tests, you should use the gradle flag `android.testInstrumentationRunnerArguments.notAnnotation`.

Here is an example using the Testify Sample app:

```bash
./gradlew Sample:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=dev.testify.annotation.ScreenshotInstrumentation
```

Just make sure to use the appropriate, fully-qualified package name for the version of Testify you're using:
- `dev.testify.annotation.ScreenshotInstrumentation` for 2.0 and up
- `com.shopify.testify.annotation.ScreenshotInstrumentation` for 1.2.0-alpha01 and earlier


Also, congratulations on creating issue #100 🎉
