### ISSUE TITLE
Cannot run screenshotTest on Testify Sample project on Ubuntu Linux

### ISSUE THREAD

**Issue by andrew-carmichael** [ndtp/android-testify#128]
**Describe the bug**
Although I am able to build the sample application `assembleDebugAndroidTest`, I am not able to launch the tests `screenshotTest` on Ubuntu Linux. It appears that some of the gradle tasks under `testify utility` aren't working, specificially `deviceLocale`. 

This issue relates to:
- [ ] The Kotlin library
- [X] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**To Reproduce**
1. Checkout the main branch
2. run the gradle task `:LegacySample:screenshotTest`

**Expected behavior**
The screenshot tests should begin to run on the emulator.

**Screenshots**

```
andrew@desktop-ubuntu:~/src/GitHub.com/android-testify$ ./gradlew :LegacySample:screenshotTest

> Configure project :ComposeExtensions
ComposeOptions.kotlinCompilerVersion is deprecated. Compose now uses the kotlin compiler defined in your buildscript.

> Configure project :LegacySample
ComposeOptions.kotlinCompilerVersion is deprecated. Compose now uses the kotlin compiler defined in your buildscript.

> Task :LegacySample:deviceLocale FAILED

------------------------------------------------------------
Displays the device locale.
------------------------------------------------------------


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':LegacySample:deviceLocale'.
> For input string: ""

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Desktop (please complete the following information):**
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Target Android Device (please complete the following information):**
Emulator created following documentation.

**Additional context**

**Comment by DanielJette** [comment]
@andrew-carmichael Can I please get you to try running `./gradlew LegacySample:deviceLocale -Pverbose=true` and share the output?

**Comment by DanielJette** [comment]
Can not reproduce
