### ISSUE TITLE
Being able to use custom Intent extras to be available with the start of the activity

### ISSUE THREAD

**Issue by maurermax** [ndtp/android-testify#135]
Sorry for being the guy posting already the second consecutive ticket into this. But even with quite some side debugging I am not aware that the below can already be achieved right now. I am a bit split if this is a bug to the `addIntentExtras` method or rather a feature request.

Let me elaborate.

I would like to have my activity already receive given Intent extras when it is started for the first time. 

Doing the following does not work for me.

```
    var rule = ScreenshotRule(TestActivity::class.java)

   @ScreenshotInstrumentation
    @Test
    fun default() {
        rule.addIntentExtras {
            it.putString(TestActivity.EXTRA_SOME_TEST_EXTRA, "value to be there at the start")
        }
        rule.assertSame()
    }
```

the above will start the activity right away but it will not see the extra during the start.

I can fix this be choosing to not start the activity right away doing the following

```
    var rule = ScreenshotRule(TestActivity::class.java, launchActivity = false)

   @ScreenshotInstrumentation
    @Test
    fun default() {
        rule.addIntentExtras {
            it.putString(TestActivity.EXTRA_SOME_TEST_EXTRA, "value to be there at the start")
        }
        rule.assertSame()
    }
```
this will postpone the original launch until the `assertSame` call and then the extras are added correctly. 

I fail to however get the following scenario to work.
```
     var rule = ScreenshotRule(TestActivity::class.java, launchActivity = false)

   @ScreenshotInstrumentation
    @Test
    fun default() {
        rule.addIntentExtras {
            it.putString(TestActivity.EXTRA_SOME_TEST_EXTRA, "value to be there at the start")
        }
        onView(isRoot()).perform(myCustomViewAction(rule.activity, 5000))
        rule.assertSame()
    }
```
In this case rule.activity is still null as it will only get started as part of `assertSame()`. However I need to start it earlier.

I can also not do the following things for various reasons
* Using `rule.launchActivity()` to manually launch the activity will not use the generated Intent but I have to pass in an intent
* If I try to recreated the target intent completely manually (which I guess would be weird workflow) it waits for the wrong intent to come alive and times out after 45 seconds
* if I try to use `rule.getActivityIntent()` myself I cannot see the method as it is not visible on my level
* I can also not provide my own implementation of `rule.getActivityIntent()` as it is declared final

**Is your feature request related to a problem? Please describe.**
(see above)

This feedback relates to:
- [x] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**Describe the solution you'd like**
My personal expected behavior would be that add intent extras actually would still act on the activity before the actual start is happening. If this is not possible I would want to see a method to provide start intent changes somehow differently.

**Describe alternatives you've considered**
(see above)

**Additional context**
Happy to provide more context or example code where needed.

**Comment by DanielJette** [comment]
Hi @maurermax I appreciate the feedback. The current vision for Testify is for it to be highly customizable and flexible to meet the needs of as many use-cases as possible. So, I sincerely appreciate the opportunity to help you with your use-case.

I'm not in a position at the moment to code up a test that I can debug locally, but looking only at your comment above, I believe that the solution to your problem will be to make use of the [`setExpressoActions()`](https://github.com/ndtp/android-testify/blob/main/Library/src/main/java/dev/testify/ScreenshotRule.kt#L174) builder method on `ScreenshotRule`. This method was specifically added to allow you the opportunity to interact with an activity after it has been inflated and the intents applied. It's supposed to be called at the right time, respecting the Activity lifecycle and allowing you to ensure the Activity is loaded with extras first.

You can see an example of `setExpressoActions` [here](https://github.com/ndtp/android-testify/blob/main/Samples/Legacy/src/androidTest/java/dev/testify/sample/ScreenshotRuleExampleTests.kt#L145-L167).

Taking your code from above, perhaps you can try this and see if it works for you?:

```kotlin
   var rule = ScreenshotRule(TestActivity::class.java, launchActivity = false)

   @ScreenshotInstrumentation
    @Test
    fun default() {
        rule
            .addIntentExtras {
                it.putString(TestActivity.EXTRA_SOME_TEST_EXTRA, "value to be there at the start")
            }
            .setExpressoActions {
                onView(isRoot()).perform(myCustomViewAction(rule.activity, 5000))
            }
            .assertSame()
    }
```

**Comment by DanielJette** [comment]
Oh, one other thing @maurermax. If you have not already, you may want to consider upgrading to Testify 2.0.0-beta02 as this version no longer requires the use of the `launchActivity` flag.

**Comment by maurermax** [comment]
The approache with the chained calls and the `beta01` (I couldn't load beta02) works perfectly fine. I someone wasn't aware that this is the preferred way of chaining the whole test buildup into one call as I haven't seen it like this with other espresso test examples I have been coming across. 

But never mind. Thanks for the explanation here.
