### ISSUE TITLE
Does testify support gradle managed devices?

### ISSUE THREAD

**Issue by kpateldev** [ndtp/android-testify#136]
Is there any documentation on how to use gradle-managed devices on Testify?  https://developer.android.com/studio/test/gradle-managed-devices

**Comment by DanielJette** [comment]
Hi @kpateldev.
Thanks for the question.
There is a ticket to investigate and support that here https://github.com/ndtp/android-testify/issues/7

I do not anticipate supporting that in the 2.0 release timeframe.

It would be helpful if you could comment on https://github.com/ndtp/android-testify/issues/7 that you would like to see support added for Managed Devices. It would also be helpful for you to outline what functionality you'd expect from Testify and how you'd like it to leverage Managed Devices in your workflow.
