### ISSUE TITLE
Plugin [id: 'dev.testify', version: '2.0.0-beta01'] was not found in any of the following sources.

### ISSUE THREAD

**Issue by DanielJette** [ndtp/android-testify#137]
**Describe the bug**

This issue relates to:
- [ ] The Kotlin library
- [x] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**To Reproduce**

In your `build.gradle`

```
plugins {
    id("dev.testify") version "2.0.0-beta01"
}
```

**Expected behavior**

The plugin is applied

**Actual behavior**

Error:
`Plugin [id: 'dev.testify', version: '2.0.0-beta01'] was not found in any of the following sources.`

**Comment by DanielJette** [comment]
@jaredh we ran into this at work today. Do remember what we need to change to support this?

**Comment by mtrewartha** [comment]
@DanielJette Did you ever find out what this was caused by or how to work around it?

**Comment by DanielJette** [comment]
@mtrewartha We're still working to publish a permanent fix to this.

In the meantime, the work around is to use the old-school `classpath` entry in your `build.gradle`
Even if you use the modern plugin configuration for your other plugins, you can still add this to your root build.gradle:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "dev.testify:plugin:2.0.0-beta01"
    }
}
```

And use `apply plugin: 'dev.testify'` in your app module `build.gradle` like [this](https://github.com/ndtp/android-testify/blob/main/Samples/Flix/build.gradle#L24)
