### ISSUE TITLE
Composable test results not included in test results yml

### ISSUE THREAD

**Issue by kpateldev** [ndtp/android-testify#152]
I'm running into an issue where tests using ComposableScreenshotRule to test composables don't include test results in the test results yml file - is there another step to get these included in the run? It would also be great to get additional metrics like test run time included in the results file.

**Comment by DanielJette** [comment]
Hello @kpateldev
Thanks for the bug report. The Legacy Sample enables the reporter output and I can see that it's capturing the state for the ComposableScreenshotRule tests, so I suspect what you're running into is a bug in the reporter feature enabling.

The Legacy Sample enables the reporter via the Manifest file as seen here: https://github.com/ndtp/android-testify/blob/main/Samples/Legacy/src/androidTest/AndroidManifest.xml#L6

How are you enabling it? I suspect there's an issue with the test rule constructor.
