### ISSUE TITLE
Make Gradle managed device output folders be named according to Testify naming strategy

### ISSUE THREAD

**Issue by olegosipenko** [ndtp/android-testify#175]
**Is your feature request related to a problem? Please describe.**
Testify supports various locales and screen orientations by encoding that information into the directory name (device key, eg. `30-1080x2220@440dp-en_US`). This information is lost in the GMD `managed_device_android_test_additional_output directory`. It would be beneficial to improve the file output for the `Test Storage` destination to preserve this information
Similar to above, it would be handy to preserve the device key as part of the `managed_device_android_test_additional_output` so that it would be easier to copy the screenshots to the proper assets directory

This feedback relates to:
- [x] The Kotlin library
- [x] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [x] The sample code
- [x] The documentation

**Describe the solution you'd like**

**Describe alternatives you've considered**
When running GMD, screenshots are stored in the managed_device_android_test_additional_output directory in the folder named after the name of the device given in the managedDevices clojure in the build.gradle file.
So, we have two options:
- either suggest user to name device following naming convention VERSION-WIDTHxHEIGHT@DENSITY-LOCALE
- or run some script after gradle task to rename the folder

**Comment by DanielJette** [comment]
I have a pretty good idea on how to do this pretty easily. I'll work on it this week.
