### ISSUE TITLE
IntelliJ Platform plung not working with latest Android Studio Jellyfish

### ISSUE THREAD

**Issue by ydonev** [ndtp/android-testify#204]
**Describe the bug**

This issue relates to:
- [ ] The Kotlin library
- [ ] The Gradle plugin
- [x] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**To Reproduce**
With latest version (Android Studio Jellyfish | 2023.3.1 Canary 9), plugin cannot be installed nor use

**Expected behavior**
Installing and using the plugin with latest AS version.

**Screenshots**
N\A

**Desktop (please complete the following information):**
Android Studio Jellyfish on Windows and MAC

**Target Android Device (please complete the following information):**
N\A

**Additional context**
N\A

**Comment by DanielJette** [comment]
Thanks for logging this issue @ydonev 
I hadn't noticed that Jellyfish was already available in preview. I have updated the Intellij plugin to support Jellyfish and have submitted the changes for review by JetBrains. I expect the plugin to be published within 7 days.

**Comment by ydonev** [comment]
I can confirmed that the plug in is available in the Marketplace, I was able to install it and works as expected.
I will closed the issue and thanks again.
