### ISSUE TITLE
Plugin not compatible with latest Canary version of Android Studio

### ISSUE THREAD

**Issue by Dukoff92** [ndtp/android-testify#233]
Hello,

Just a heads up that version 2.3.1 of Android Testify plugin is not compatible with the latest Android Studio Ladybug 2024.2.1 Canary 9 (Build #AI-242.20224.300.2421.12293307).

**Comment by DanielJette** [comment]
Thanks for the bug report @Dukoff92 
An updated was submitted on 2024-09-02 and is pending approval by Jetbrains

**Comment by Dukoff92** [comment]
Thanks for the swift reaction!

**Comment by DanielJette** [comment]
@Dukoff92 2.4 should be available from the Intellij Marketplace now
