### ISSUE TITLE
Update docs/sample to include how to run in non-app modules (e.g. Android library module)

### ISSUE THREAD

**Issue by DanielJette** [ndtp/android-testify#90]
**Is your feature request related to a problem? Please describe.**
I'd like to know how to get the tests working in a non-app module such as an Android library module. Would be fantastic if the docs mentioned how to do this, and even better some sample code to demonstrate it.

This feedback relates to:
- [x] The Kotlin library
- [x] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [x] The sample code
- [x] The documentation

**Describe the solution you'd like**
As mentioned above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

---

_Copied from @ryansama https://github.com/Shopify/android-testify/issues/272_

**Comment by DanielJette** [comment]
Hi @ryansama
Thanks for the feedback! I have plans to create full documentation on how to use Testify with an Android Library module project. Those documents aren't quite ready yet, but I do have a work-in-progress branch where I had added a library module to the Sample app. I just opened that as a draft that you can take a look at here https://github.com/Shopify/android-testify/pull/273

Most likely, you'll want to look at the gradle configuration here:

https://github.com/Shopify/android-testify/pull/273/files#diff-7be9b607348050f71804f7ca41acb93b9b6434014f095c19f3264d2127b87c14R53-R56

**Comment by DanielJette** [comment]
_Copied from https://github.com/Shopify/android-testify/issues/272#issuecomment-1159292799_

That seemed to work very well, it wasn't too clear what exactly I should name the application/package, thank you!

**Comment by sergio-sastre** [comment]
Hi @DanielJette !

I'm trying to add android-testify to [Android Screenshot Testing Playground](https://github.com/sergio-sastre/Android-screenshot-testing-playground)

However, I'm finding the following issue
<img width="850" alt="Screenshot 2023-10-01 at 22 36 24" src="https://github.com/ndtp/android-testify/assets/6097181/a6b18957-159e-434a-a736-3c5e08474c14">

You can reproduce this in the branch "feature/add_android_testify_lib" by running "./gradlew :recyclerviewscreen:android-testify:screenshotRecord"

It is a library submodule (i.e. module inside a module), so I'm wondering whether I actually configured testify right.
```groovy
testify {
    applicationPackageId 'com.example.road.to.effective.snapshot.testing'
    testPackageId 'com.example.road.to.effective.snapshot.testing'
}
```

You can take a look at the [full gradle file here](https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/feature/add_android_testify_lib/recyclerviewscreen/android-testify/build.gradle)

I also added the classpath in the [project gradle file](https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/feature/add_android_testify_lib/build.gradle)

Any idea what could be the issue?

**Comment by DanielJette** [comment]
@sergio-sastre I'll try checking out the code later when I have a bit more time, but just looking at the output you shared, I would guess that the issue is that Testify is not inferring the module names correctly and is not invoking the proper Gradle dependencies.

To address this, you can add `moduleName ":recyclerviewscreen:android-testify"` to the `testify` closure in your `build.gradle`

Give that a try and let me know if it helps!

**Comment by sergio-sastre** [comment]
> @sergio-sastre I'll try checking out the code later when I have a bit more time, but just looking at the output you shared, I would guess that the issue is that Testify is not inferring the module names correctly and is not invoking the proper Gradle dependencies.
> 
> To address this, you can add `moduleName ":recyclerviewscreen:android-testify"` to the `testify` closure in your `build.gradle`
> 
> Give that a try and let me know if it helps!

@DanielJette 
Wow! Thank you very much, that did work indeed!

However, the app must not be previously installed, otherwise I get
```groovy
* What went wrong:
Execution failed for task ':recyclerviewscreen:android-testify:installDebugAndroidTest'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_VERSION_DOWNGRADE
```
might be because the appId and the testappId are the same... I guess?

**Comment by DanielJette** [comment]
>might be because the appId and the testappId are the same... I guess?

@sergio-sastre Yes, that could be a reason for this error.
For a library module project, the test APK and the "app" APK should be the same. Maybe you have another project that's using the same applicationId?

If you manually run `:recyclerviewscreen:android-testify:installDebug` and then `:recyclerviewscreen:android-testify:installDebugAndroidTest`, do you get any errors?

**Comment by sergio-sastre** [comment]
> > might be because the appId and the testappId are the same... I guess?
> 
> @sergio-sastre Yes, that could be a reason for this error. For a library module project, the test APK and the "app" APK should be the same. Maybe you have another project that's using the same applicationId?
> 
> If you manually run `:recyclerviewscreen:android-testify:installDebug` and then `:recyclerviewscreen:android-testify:installDebugAndroidTest`, do you get any errors?

Yes, I do, exactly the same error for both commands
