### ISSUE TITLE
Font scale configuration for Compose tests

### ISSUE THREAD

**Issue by ryansama** [ndtp/android-testify#95]
**Is your feature request related to a problem? Please describe.**
Absolutely love that we can configure font scales by creating our own test activity that implements `TestifyResourcesOverride`.  Would be great to update [`ComposableTestActivity`](https://github.com/ndtp/android-testify/blob/main/Ext/Compose/src/main/java/dev/testify/ComposableTestActivity.kt) to implement `TestifyResourcesOverride` so that font scale or locale can be configured out-of-the-box for Jetpack Compose tests.

This feedback relates to:
- [x] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**Describe the solution you'd like**
Update `ComposableTestActivity` to implement `TestifyResourcesOverride` so that font scale or locale can be configured for Jetpack Compose tests.

**Describe alternatives you've considered**
Alternatively we could update `ComposableScreenshotRule` to optionally accept a custom activity, much like `ScreenshotRule`.

**Additional context**
N/A

**Comment by DanielJette** [comment]
Hi @ryansama. Thanks for the feature request. This is a great idea and I think it should be straightforward to add. I'll add this to our backlog for the 2.0 final release.

**Comment by DanielJette** [comment]
Fix for this was published in `2.0.0-alpha02`
